const phrases = [
  "Muchas gracias por confiar en nosotros",
  "Agradezco mucho tu preferencia",
  "Te agradezco infinitamente por elegirnos",
  "Gracias por hacernos parte de tu vida",
  "Estamos agradecidos por tu apoyo",
  "Tu preferencia es la mayor recompensa",
  "Muchas gracias por tu apoyo",
  "Gracias por confiar en nosotros",
  "Te agradezco de corazon por elegirnos",
  "Estamos eternamente agradecidos por tu elecci n",
  "Gracias por hacernos parte de tu rutina",
  "Muchas gracias por tu fidelidad",
  "Agradezco mucho tu amistad",
  "Gracias por todo el apoyo que nos brindas",
  "Agradezco de corazon tu presencia en nuestra app",
  "Eres increible, gracias por todo",
  "Muchas gracias por darme la oportunidad de servirte",
  "Gracias por creer en nosotros",
  "Gracias por tu apoyo incondicional",
  "Eres muy amable al elegirnos",
  "Agradezco mucho tu confianza",
  "Gracias por tu generosidad",
  "Eres una gran persona por elegirnos",
  "Gracias por tu ayuda",
  "Tu apoyo es muy valioso para nosotros",
  "Gracias por tu amistad",
  "Gracias por darnos la oportunidad de servirte",
  "Gracias por tu fidelidad",
  "Gracias por tu confianza en nosotros",
  "Gracias por tu preferencia",
];

export default phrases;
